import{useMemo,useState}from'react';import * as XLSX from'xlsx';import{Browser}from'@capacitor/browser';import{parseDelimited,parseSheetRows,parseText}from'./parser';import type{ParsedWord}from'./parser';

type Word=ParsedWord;type View='en'|'zh'|'both';
type Book={id:string;name:string;pageSize:number;words:Word[];whitelist:Record<string,string[]>};
const BOOKS_KEY='wd_books_v2',OLD_KEY='wd_words',REPO='RT-C-6668882025/word-dictation',PROJECT_URL='https://github.com/'+REPO,RELEASE_API='https://api.github.com/repos/'+REPO+'/releases/latest';
const VERSION='0.3.0',BUILD_SHA=import.meta.env.VITE_COMMIT_SHA||'dev';const demo='abandon,放弃\nability,能力\nabsent,缺席的\nabsolute,绝对的\naccept,接受\nachieve,达到';
const uid=()=>Math.random().toString(36).slice(2),pageKey=(n:number)=>String(n);const fixedCounts=[10,20,30,40,50];
function makeBook(words:Word[],name:string,pageSize:number):Book{const whitelist:Record<string,string[]>={};for(let i=0;i<words.length;i+=pageSize)whitelist[pageKey(i/pageSize)]=words.slice(i,i+pageSize).map(w=>w.id);return{id:uid(),name:name.trim()||'未命名词库',pageSize,words,whitelist}}
function loadBooks():Book[]{try{const saved=JSON.parse(localStorage.getItem(BOOKS_KEY)||'[]');if(Array.isArray(saved)&&saved.length)return saved}catch{}try{const old:Word[]=JSON.parse(localStorage.getItem(OLD_KEY)||'[]');if(old.length){const b=makeBook(old,'我的词库',50);localStorage.setItem(BOOKS_KEY,JSON.stringify([b]));return[b]}}catch{}return[]}
function clampPage(book:Book,n:number){return Math.max(0,Math.min(n,Math.ceil(book.words.length/book.pageSize)-1))}
function GitHubMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .7a11.5 11.5 0 0 0-3.64 22.41c.58.1.79-.25.79-.56v-2.23c-3.22.7-3.9-1.37-3.9-1.37-.53-1.34-1.29-1.7-1.29-1.7-1.05-.72.08-.71.08-.71 1.17.08 1.78 1.2 1.78 1.2 1.04 1.77 2.72 1.26 3.38.96.1-.75.4-1.26.74-1.55-2.57-.29-5.27-1.28-5.27-5.68 0-1.25.45-2.28 1.19-3.08-.12-.29-.52-1.46.11-3.04 0 0 .97-.31 3.16 1.18A10.98 10.98 0 0 1 12 6.14c.98 0 1.95.13 2.87.39 2.19-1.49 3.15-1.18 3.15-1.18.64 1.58.24 2.75.12 3.04.74.8 1.19 1.83 1.19 3.08 0 4.41-2.71 5.38-5.29 5.67.42.36.79 1.06.79 2.14v3.27c0 .31.21.67.8.56A11.5 11.5 0 0 0 12 .7Z"/></svg>}
export default function App(){
 const[books,setBooks]=useState<Book[]>(loadBooks);const[screen,setScreen]=useState<'library'|'import'|'study'|'about'>(books.length?'library':'import');const[activeId,setActiveId]=useState(books[0]?.id||'');const[page,setPage]=useState(0);const[batchIds,setBatchIds]=useState<string[]>([]);const[seen,setSeen]=useState<Set<string>>(new Set());const[views,setViews]=useState<Record<string,View>>({});const[baseView,setBaseView]=useState<View>('zh');const[batchSize,setBatchSize]=useState(20);const[customSize,setCustomSize]=useState(20);const[checking,setChecking]=useState(false);
 const book=books.find(b=>b.id===activeId)||null;
 const persist=(next:Book[])=>{setBooks(next);localStorage.setItem(BOOKS_KEY,JSON.stringify(next))};
 const updateBook=(fn:(b:Book)=>Book)=>{if(!book)return;persist(books.map(b=>b.id===book.id?fn(b):b))};
 const pageWords=useMemo(()=>book?book.words.slice(page*book.pageSize,(page+1)*book.pageSize):[],[book,page]);
 const whiteIds=useMemo(()=>new Set(book?.whitelist[pageKey(page)]||[]),[book,page]);
 const needWords=useMemo(()=>pageWords.filter(w=>whiteIds.has(w.id)),[pageWords,whiteIds]);
 const remaining=useMemo(()=>needWords.filter(w=>!seen.has(w.id)&&!batchIds.includes(w.id)),[needWords,seen,batchIds]);
 const batch=useMemo(()=>{const ids=new Set(batchIds);return pageWords.filter(w=>ids.has(w.id))},[pageWords,batchIds]);
 const pageCount=book?Math.ceil(book.words.length/book.pageSize):0,mastered=pageWords.length-needWords.length;
 const resetSession=(b:Book,p:number,size=batchSize,view=baseView)=>{const cp=clampPage(b,p),pw=b.words.slice(cp*b.pageSize,(cp+1)*b.pageSize),wl=new Set(b.whitelist[pageKey(cp)]||[]),safe=Math.max(1,size),ids=pw.filter(w=>wl.has(w.id)).slice(0,safe).map(w=>w.id);setPage(cp);setSeen(new Set());setBatchIds(ids);setViews(Object.fromEntries(ids.map(id=>[id,view])));setBatchSize(safe);setCustomSize(safe)};
 const openBook=(b:Book)=>{setActiveId(b.id);resetSession(b,0);setScreen('study')};
 const addBook=(words:Word[],name:string,pageSize:number)=>{if(!words.length)return alert('没有识别到“英文 + 中文”数据');const b=makeBook(words,name,pageSize);persist([...books,b]);setActiveId(b.id);resetSession(b,0);setScreen('study')};
 const importRaw=(raw:string)=>{const name=(document.getElementById('bookName')as HTMLInputElement)?.value||'我的词库',ps=Number((document.getElementById('pageSize')as HTMLInputElement)?.value)||50;addBook(parseText(raw),name,Math.max(10,Math.min(200,ps)))};
 const file=async(f:File)=>{const name=(document.getElementById('bookName')as HTMLInputElement)?.value||f.name.replace(/\.[^.]+$/,''),ps=Math.max(10,Math.min(200,Number((document.getElementById('pageSize')as HTMLInputElement)?.value)||50));let w:Word[]=[];if(/\.xlsx?$/i.test(f.name)){const wb=XLSX.read(await f.arrayBuffer());const rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});w=parseSheetRows(rows)}else{const raw=await f.text();w=/\.csv$/i.test(f.name)?parseDelimited(raw):/\.tsv$/i.test(f.name)?parseDelimited(raw,'\t'):parseText(raw)}addBook(w,name,ps)};
 const setAllViews=(v:View)=>{setBaseView(v);setViews(x=>({...x,...Object.fromEntries(batchIds.map(id=>[id,v]))}))};
 const cycleView=(id:string)=>setViews(v=>({...v,[id]:v[id]==='zh'?'both':v[id]==='both'?'en':'zh'}));
 const toggleNeed=(id:string)=>updateBook(b=>{const k=pageKey(page),s=new Set(b.whitelist[k]||[]);s.has(id)?s.delete(id):s.add(id);return{...b,whitelist:{...b.whitelist,[k]:[...s]}}});
 const setBatchNeed=(need:boolean)=>updateBook(b=>{const k=pageKey(page),s=new Set(b.whitelist[k]||[]);batchIds.forEach(id=>need?s.add(id):s.delete(id));return{...b,whitelist:{...b.whitelist,[k]:[...s]}}});
 const showCurrent=(size:number)=>{if(book)resetSession(book,page,Math.min(Math.max(1,size),Math.max(1,needWords.length)))};
 const nextBatch=(size=batchSize)=>{if(!book)return;const liveWhite=new Set(book.whitelist[pageKey(page)]||[]),done=new Set([...seen,...batchIds]),candidates=pageWords.filter(w=>liveWhite.has(w.id)&&!done.has(w.id));if(!candidates.length)return;const safe=Math.min(Math.max(1,size),candidates.length),ids=candidates.slice(0,safe).map(w=>w.id);setSeen(done);setBatchIds(ids);setViews(v=>({...v,...Object.fromEntries(ids.map(id=>[id,baseView]))}));setBatchSize(size);setCustomSize(size)};
 const changePage=(n:number)=>{if(book)resetSession(book,n)};
 const renameBook=(id:string,current:string)=>{const next=prompt('重命名词库',current)?.trim();if(!next||next===current)return;persist(books.map(b=>b.id===id?{...b,name:next}:b))};
 const deleteBook=(id:string)=>{const next=books.filter(b=>b.id!==id);persist(next);if(activeId===id)setActiveId(next[0]?.id||'');if(!next.length)setScreen('import')};
 const openUrl=(url:string)=>Browser.open({url});
 const checkUpdate=async()=>{setChecking(true);try{const r=await fetch(RELEASE_API,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error();const rel=await r.json(),apk=rel.assets?.find((a:{name:string})=>a.name.endsWith('.apk'));if(rel.target_commitish===BUILD_SHA){alert('已经是最新版')}else if(apk&&confirm('发现新版本，下载最新 APK？'))await openUrl(apk.browser_download_url);else if(!apk)await openUrl(PROJECT_URL+'/releases/latest')}catch{alert('检查更新失败，请稍后再试')}finally{setChecking(false)}};
 if(screen==='about')return <main className="shell"><header><div><b>ABOUT</b><span>Open-source · Local-first</span></div><button className="ghost" onClick={()=>setScreen(books.length?'library':'import')}>← 首页</button></header><section className="about"><div className="aboutHero"><div className="aboutMark">WD</div><div className="aboutIdentity"><span className="eyebrow">WORD DICTATION</span><h1>把默写这件事，<br/>做得足够简单。</h1><p>为实体手写板设计。没有账号，没有云端，没有多余流程。词库留在你的设备里。</p></div></div><div className="projectCard"><div className="githubBadge"><span className="githubIcon"><GitHubMark/></span><div><b>{REPO}</b><span>Open source on GitHub</span></div><span className="openArrow">↗</span></div><button className="projectHit" onClick={()=>openUrl(PROJECT_URL)} aria-label="打开 GitHub 项目"/></div><div className="aboutMeta"><div><span>VERSION</span><b>v{VERSION}</b><small>{BUILD_SHA.slice(0,7)}</small></div><div><span>AUTHOR</span><b>RT-C-6668882025</b><small>GitHub</small></div><div><span>STORAGE</span><b>Local only</b><small>无账号 · 无后端</small></div></div><div className="aboutActions"><button className="primary updateButton" disabled={checking} onClick={checkUpdate}><span>{checking?'正在连接 GitHub…':'检查更新'}</span><small>{checking?'请稍候':'GitHub Release'}</small></button><button onClick={()=>openUrl(PROJECT_URL)}><span className="buttonIcon"><GitHubMark/></span>查看源代码</button><button onClick={()=>openUrl(PROJECT_URL+'/releases/latest')}>最新 APK ↗</button></div><div className="aboutFoot"><span>Built for handwriting, not another flashcard app.</span><b>© 2026 RT-C-6668882025</b></div></section></main>;
 if(screen==='library')return <main className="shell"><header><div><b>WORD DICTATION</b><span>{books.length} 个词库</span></div><div className="headerActions"><button className="ghost" onClick={()=>setScreen('about')}>关于</button><button className="primary" onClick={()=>setScreen('import')}>+ 新建词库</button></div></header><section className="books">{books.map(b=>{const pages=Math.ceil(b.words.length/b.pageSize),need=Object.values(b.whitelist).reduce((n,a)=>n+a.length,0);return <article className="book" key={b.id} onClick={()=>openBook(b)}><div><strong>{b.name}</strong><span>{b.words.length} 词 · {pages} 页 · 每页 {b.pageSize}</span></div><div className="bookRight"><b>{need}</b><span>需要背</span><button className="ghost mini" onClick={e=>{e.stopPropagation();renameBook(b.id,b.name)}}>重命名</button><button className="ghost mini danger" onClick={e=>{e.stopPropagation();if(confirm('删除词库“'+b.name+'”？'))deleteBook(b.id)}}>删除</button></div></article>})}</section></main>;
 if(screen==='import')return <main className="shell"><header><div><b>新建词库</b><span>导入后自动固定分页</span></div><div className="headerActions"><button className="ghost" onClick={()=>setScreen('about')}>关于</button>{books.length>0&&<button className="ghost" onClick={()=>setScreen('library')}>← 首页</button>}</div></header><section className="import"><div className="importMeta"><label>词库名称<input id="bookName" placeholder="例如：专升本核心词汇"/></label><label>每页单词数<input id="pageSize" type="number" min="10" max="200" defaultValue="50"/></label></div><p>支持 TXT / CSV / Excel / Markdown。每页默认 50 个，导入后页码和单词位置固定。</p><textarea id="raw" defaultValue={demo}/><div className="row"><button className="primary" onClick={()=>importRaw((document.getElementById('raw')as HTMLTextAreaElement).value)}>创建词库</button><label className="file">选择文件<input type="file" accept=".txt,.csv,.tsv,.md,.markdown,.xlsx,.xls" onChange={e=>e.target.files?.[0]&&file(e.target.files[0])}/></label></div></section></main>;
 if(!book)return null;
 const batchNeed=batch.filter(w=>whiteIds.has(w.id)).length,nextOptions=fixedCounts.filter(n=>n<=remaining.length);if(remaining.length&&!nextOptions.includes(remaining.length))nextOptions.push(remaining.length);nextOptions.sort((a,b)=>a-b);
 return <main className="shell"><header><div><b>{book.name}</b><span>{book.words.length} 词 · 第 {page+1}/{pageCount} 页</span></div><div className="headerActions"><button className="ghost homeBtn" onClick={()=>setScreen('library')}>← 首页</button><button className="ghost" disabled={page===0} onClick={()=>changePage(page-1)}>← 上一页</button><button className="ghost" disabled={page>=pageCount-1} onClick={()=>changePage(page+1)}>下一页 →</button></div></header>
 <nav className="studyNav"><div className="navGroups"><div className="seg">{([['zh','中文'],['en','英文'],['both','全部']]as const).map(([v,t])=><button key={v} className={baseView===v?'on':''} onClick={()=>setAllViews(v)}>{t}</button>)}</div><div className="countControl"><span>显示</span>{fixedCounts.map(n=><button key={n} disabled={!needWords.length} className={batch.length===Math.min(n,needWords.length)&&batchSize===n?'on':''} onClick={()=>showCurrent(n)}>{n}</button>)}<input aria-label="自定义显示数量" type="number" min="1" max={Math.max(1,needWords.length)} value={customSize} onChange={e=>setCustomSize(Math.max(1,Number(e.target.value)||1))}/><button onClick={()=>showCurrent(customSize)} disabled={!needWords.length}>自定义</button></div></div><div className="pageStats"><span>本页 {pageWords.length}</span><span>需要背 <b>{needWords.length}</b></span><span>已会 {mastered}</span><span>本批 {batch.length}</span><span>剩余 {remaining.length}</span></div></nav>
 {batch.length?<section className="grid">{batch.map(w=>{const v=views[w.id]||baseView,on=whiteIds.has(w.id);return <article key={w.id} className={on?'card':'card mastered'}><span className="num">{String(page*book.pageSize+pageWords.indexOf(w)+1).padStart(3,'0')}</span><button className="word" onClick={()=>cycleView(w.id)} title="点按切换该词显示"><strong className={v==='zh'?'hiddenWord':''}>{w.en}</strong><span className={v==='en'?'answer hiddenWord':'answer'}>{w.zh}</span></button><button className={on?'need on':'need'} onClick={()=>toggleNeed(w.id)}>{on?'需要背':'已会'}</button></article>})}</section>:<section className="empty"><h2>{needWords.length?'选择显示数量':'本页白名单已清空。'}</h2><p>{needWords.length?'选择 10–50 或输入自定义数量。':'这一页已经没有需要背的单词。'}</p></section>}
 <footer><div className="footerLeft"><button onClick={()=>setBatchNeed(false)} disabled={!batchNeed}>本批已会</button><button onClick={()=>setBatchNeed(true)} disabled={batchNeed===batch.length}>本批加入白名单</button><span>白名单 {needWords.length} · 剩余 {remaining.length}</span></div>{remaining.length>0?<div className="nextSizes"><span>下一批</span>{nextOptions.map(n=><button key={n} className={n===Math.min(batchSize,remaining.length)?'primary':''} onClick={()=>nextBatch(n)}>{n}</button>)}<input aria-label="下一批自定义数量" type="number" min="1" max={remaining.length} value={customSize} onChange={e=>setCustomSize(Math.max(1,Number(e.target.value)||1))}/><button onClick={()=>nextBatch(customSize)}>自定义</button></div>:page<pageCount-1?<button className="primary" onClick={()=>changePage(page+1)}>下一页 →</button>:<button className="primary" onClick={()=>setScreen('library')}>完成并返回首页</button>}</footer>
 </main>
}
