import{useEffect,useMemo,useRef,useState}from'react';import * as XLSX from'xlsx';import * as mammoth from'mammoth/mammoth.browser';import{getDocument,GlobalWorkerOptions}from'pdfjs-dist';import pdfWorker from'pdfjs-dist/build/pdf.worker.min.mjs?url';import'./vendor/docToText.js';import{Browser}from'@capacitor/browser';import{Capacitor,registerPlugin}from'@capacitor/core';import{Preferences}from'@capacitor/preferences';import{App as CapacitorApp}from'@capacitor/app';import{parseDelimited,parseSheetRows,parseText}from'./parser';import type{ParsedWord}from'./parser';

import{usePullRefresh}from'./usePullRefresh';

type Word=ParsedWord;type View='en'|'zh'|'both';
type Book={id:string;name:string;pageSize:number;words:Word[];whitelist:Record<string,string[]>};
const BOOKS_KEY='wd_books_v2',OLD_KEY='wd_words',REPO='RT-C-6668882025/word-dictation',PROJECT_URL='https://github.com/'+REPO,RELEASE_API='https://api.github.com/repos/'+REPO+'/releases/latest';
GlobalWorkerOptions.workerSrc=pdfWorker;const PocketTts=registerPlugin<any>('PocketTts');const AppUpdater=registerPlugin<any>('AppUpdater');type TtsStatus={installed:boolean;downloading:boolean;model?:string;downloadMB?:number;diskMB?:number};
function SpeakerIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9v6h4l5 4V5L8 9H4Z" fill="currentColor"/><path d="M16 8.5c1.4 1.8 1.4 5.2 0 7M18.7 6c3 3.3 3 8.7 0 12" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>}
const VERSION='0.4.27',DIRECT_APK='https://github.com/RT-C-6668882025/word-dictation/releases/download/latest/word-dictation.apk',BUILD_SHA=import.meta.env.VITE_COMMIT_SHA||'dev';const demo='abandon,放弃\nability,能力\nabsent,缺席的\nabsolute,绝对的\naccept,接受\nachieve,达到';
const uid=()=>Math.random().toString(36).slice(2),pageKey=(n:number)=>String(n);const fixedCounts=[10,20,30,40,50];
function makeBook(words:Word[],name:string,pageSize:number):Book{const whitelist:Record<string,string[]>={};for(let i=0;i<words.length;i+=pageSize)whitelist[pageKey(i/pageSize)]=words.slice(i,i+pageSize).map(w=>w.id);return{id:uid(),name:name.trim()||'未命名词库',pageSize,words,whitelist}}
function loadBooks():Book[]{try{const saved=JSON.parse(localStorage.getItem(BOOKS_KEY)||'[]');if(Array.isArray(saved)&&saved.length)return saved}catch{}try{const old:Word[]=JSON.parse(localStorage.getItem(OLD_KEY)||'[]');if(old.length){const b=makeBook(old,'我的词库',50);localStorage.setItem(BOOKS_KEY,JSON.stringify([b]));return[b]}}catch{}return[]}
function clampPage(book:Book,n:number){return Math.max(0,Math.min(n,Math.ceil(book.words.length/book.pageSize)-1))}
function GitHubMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .7a11.5 11.5 0 0 0-3.64 22.41c.58.1.79-.25.79-.56v-2.23c-3.22.7-3.9-1.37-3.9-1.37-.53-1.34-1.29-1.7-1.29-1.7-1.05-.72.08-.71.08-.71 1.17.08 1.78 1.2 1.78 1.2 1.04 1.77 2.72 1.26 3.38.96.1-.75.4-1.26.74-1.55-2.57-.29-5.27-1.28-5.27-5.68 0-1.25.45-2.28 1.19-3.08-.12-.29-.52-1.46.11-3.04 0 0 .97-.31 3.16 1.18A10.98 10.98 0 0 1 12 6.14c.98 0 1.95.13 2.87.39 2.19-1.49 3.15-1.18 3.15-1.18.64 1.58.24 2.75.12 3.04.74.8 1.19 1.83 1.19 3.08 0 4.41-2.71 5.38-5.29 5.67.42.36.79 1.06.79 2.14v3.27c0 .31.21.67.8.56A11.5 11.5 0 0 0 12 .7Z"/></svg>}
export default function App(){
 const[books,setBooks]=useState<Book[]>(loadBooks);const[screen,setScreen]=useState<'library'|'import'|'study'|'about'|'index'>(books.length?'library':'import');const[activeId,setActiveId]=useState(books[0]?.id||'');const[page,setPage]=useState(0);const[batchIds,setBatchIds]=useState<string[]>([]);const[seen,setSeen]=useState<Set<string>>(new Set());const[views,setViews]=useState<Record<string,View>>({});const[baseView,setBaseView]=useState<View>('zh');const[batchSize,setBatchSize]=useState(20);const[customSize,setCustomSize]=useState(20);const[checking,setChecking]=useState(false);const[updateProgress,setUpdateProgress]=useState<{progress:number;state:string;source:string}|null>(null);const[ttsMenu,setTtsMenu]=useState(false);const[ttsStatus,setTtsStatus]=useState<TtsStatus>({installed:false,downloading:false});const[ttsBusy,setTtsBusy]=useState(false);const[ttsProgress,setTtsProgress]=useState(0);const[ttsState,setTtsState]=useState('');const[ttsSpeed,setTtsSpeed]=useState(()=>Number(localStorage.getItem('wd_tts_speed')||'1'));const[ttsVoice,setTtsVoice]=useState(()=>Math.max(0,Math.min(7,Number(localStorage.getItem('wd_tts_voice')||'1'))));const[pendingUpdate,setPendingUpdate]=useState(false);const[indexQuery,setIndexQuery]=useState('');const[indexPage,setIndexPage]=useState<number|null>(null);const[playbackEngine,setPlaybackEngine]=useState(()=>localStorage.getItem('wd_playback_engine')==='offline'?'offline':'system');
 const[showAll,setShowAll]=useState(false),[listDirty,setListDirty]=useState(false),[refreshNotice,setRefreshNotice]=useState('');
 const voiceDialog=useRef<HTMLDialogElement>(null),voiceTrigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{
  if(!ttsMenu)return;
  const dialog=voiceDialog.current;if(!dialog)return;
  dialog.showModal();
  const previous=document.body.style.overflow;document.body.style.overflow='hidden';
  return()=>{dialog.close();document.body.style.overflow=previous;voiceTrigger.current?.focus({preventScroll:true})};
 },[ttsMenu]);
 useEffect(()=>{if(!refreshNotice)return;const timer=setTimeout(()=>setRefreshNotice(''),1800);return()=>clearTimeout(timer)},[refreshNotice]);
 // Reserve the rendered toolbar height, including wrapped controls and safe areas.
 useEffect(()=>{
  const footer=document.querySelector<HTMLElement>('footer');
  if(!footer)return;
  const shell=footer.closest<HTMLElement>('.shell')!;
  const measure=()=>shell.style.setProperty('--footer-height',getComputedStyle(footer).position==='fixed'?`${footer.getBoundingClientRect().height}px`:'0px');
  const observer=new ResizeObserver(measure);observer.observe(footer);measure();
  window.addEventListener('resize',measure);
  return()=>{observer.disconnect();window.removeEventListener('resize',measure)};
 },[screen]);
 useEffect(()=>{if(!Capacitor.isNativePlatform())return;let cancelled=false;(async()=>{try{const native=await Preferences.get({key:BOOKS_KEY});if(cancelled)return;if(native.value){const saved=JSON.parse(native.value) as Book[];if(Array.isArray(saved)&&saved.length&&!books.length){setBooks(saved);setActiveId(saved[0].id);setScreen('library');localStorage.setItem(BOOKS_KEY,native.value)}}else if(books.length){await Preferences.set({key:BOOKS_KEY,value:JSON.stringify(books)})}}catch{}})();return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!Capacitor.isNativePlatform())return;const h=AppUpdater.addListener('updateProgress',(p:{progress?:number;state?:string;source?:string})=>setUpdateProgress({progress:p.progress||0,state:p.state||'正在更新',source:p.source||''}));return()=>{Promise.resolve(h).then((x:any)=>x.remove()).catch(()=>{})}},[]);
 useEffect(()=>{if(!Capacitor.isNativePlatform())return;AppUpdater.getPendingUpdate().then((r:{pending?:boolean})=>setPendingUpdate(!!r.pending)).catch(()=>{})},[]);
 useEffect(()=>{if(!Capacitor.isNativePlatform())return;PocketTts.getStatus().then((s:TtsStatus)=>setTtsStatus(s)).catch(()=>{});let handle:any;PocketTts.addListener('downloadProgress',(p:{progress?:number;installed?:boolean;state?:string;source?:string})=>{if(typeof p.progress==='number')setTtsProgress(p.progress);if(p.state)setTtsState(p.state+(p.source?' · '+p.source:''));if(p.installed)setTtsStatus(s=>({...s,installed:true,downloading:false}))}).then((h:any)=>handle=h);return()=>handle?.remove?.()},[]);
 useEffect(()=>{if(!Capacitor.isNativePlatform())return;let handle:any;CapacitorApp.addListener('backButton',()=>{if(ttsMenu){setTtsMenu(false);return}if(screen!=='library'){setScreen('library');return}CapacitorApp.exitApp()}).then((h:any)=>handle=h);return()=>handle?.remove?.()},[screen,ttsMenu]);
 useEffect(()=>{if(!Capacitor.isNativePlatform()||screen==='library'||ttsMenu)return;let sx=0,sy=0,started=0,blocked=false;const start=(e:TouchEvent)=>{const t=e.target as HTMLElement;blocked=!!t.closest('input,textarea,select,.voiceMenu');if(blocked||e.touches.length!==1)return;sx=e.touches[0].clientX;sy=e.touches[0].clientY;started=Date.now()};const end=(e:TouchEvent)=>{if(blocked||!started||!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy,dt=Date.now()-started;started=0;if(dt<=900&&Math.abs(dx)>=110&&Math.abs(dx)>=Math.abs(dy)*1.6){setTtsMenu(false);setScreen('library')}};document.addEventListener('touchstart',start,{passive:true});document.addEventListener('touchend',end,{passive:true});return()=>{document.removeEventListener('touchstart',start);document.removeEventListener('touchend',end)}},[screen,ttsMenu]);
 const setVoiceSpeed=(v:number)=>{setTtsSpeed(v);localStorage.setItem('wd_tts_speed',String(v))};
 const setVoice=(v:number)=>{setTtsVoice(v);localStorage.setItem('wd_tts_voice',String(v))};
 const setPlayback=(v:string)=>{setPlaybackEngine(v);localStorage.setItem('wd_playback_engine',v)};
 const refreshTts=async()=>{if(!Capacitor.isNativePlatform())return;try{setTtsStatus(await PocketTts.getStatus())}catch{}};
 const downloadVoice=async()=>{if(!Capacitor.isNativePlatform())return alert('离线语音仅在 Android App 中可用');setTtsBusy(true);setTtsProgress(0);setTtsState('准备下载');try{await PocketTts.downloadModel({source:'auto'});await refreshTts()}catch(e:any){alert(e?.message||'语音下载失败')}finally{setTtsBusy(false);setTtsState('')}};
 const deleteVoice=async()=>{if(!confirm('删除已下载的离线语音？'))return;setTtsBusy(true);try{await PocketTts.deleteModel();await refreshTts()}catch(e:any){alert(e?.message||'删除失败')}finally{setTtsBusy(false)}};
 const speakWord=async(text:string)=>{if(!Capacitor.isNativePlatform()){const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=ttsSpeed;window.speechSynthesis.cancel();window.speechSynthesis.speak(u);return}try{if(playbackEngine==='offline'&&ttsStatus.installed)await PocketTts.speak({text,speed:ttsSpeed,sid:ttsVoice});else await PocketTts.speakSystem({text,speed:ttsSpeed,engine:''})}catch(e:any){alert(e?.message||'朗读失败')}};
 const book=books.find(b=>b.id===activeId)||null;
 const persist=(next:Book[])=>{setBooks(next);const value=JSON.stringify(next);localStorage.setItem(BOOKS_KEY,value);if(Capacitor.isNativePlatform())Preferences.set({key:BOOKS_KEY,value}).catch(()=>{})};
 const pageWords=useMemo(()=>book?book.words.slice(page*book.pageSize,(page+1)*book.pageSize):[],[book,page]);
 const whiteIds=useMemo(()=>new Set(book?.whitelist[pageKey(page)]||[]),[book,page]);
 const needWords=useMemo(()=>pageWords.filter(w=>whiteIds.has(w.id)),[pageWords,whiteIds]);
 const eligibleWords=showAll?pageWords:needWords;
 const remaining=useMemo(()=>eligibleWords.filter(w=>!seen.has(w.id)&&!batchIds.includes(w.id)),[eligibleWords,seen,batchIds]);
 const batch=useMemo(()=>{const ids=new Set(batchIds);return pageWords.filter(w=>ids.has(w.id))},[pageWords,batchIds]);
 const pageCount=book?Math.ceil(book.words.length/book.pageSize):0;
 const resetSession=(b:Book,p:number,size=batchSize,view=baseView,all=showAll)=>{const cp=clampPage(b,p),pw=b.words.slice(cp*b.pageSize,(cp+1)*b.pageSize),wl=new Set(b.whitelist[pageKey(cp)]||[]),safe=Math.max(1,size),ids=pw.filter(w=>all||wl.has(w.id)).slice(0,safe).map(w=>w.id);setListDirty(false);setPage(cp);setSeen(new Set());setBatchIds(ids);setViews(Object.fromEntries(ids.map(id=>[id,view])));setBatchSize(safe);setCustomSize(safe)};
 const refreshPage=()=>{if(book){resetSession(book,page);setRefreshNotice('已刷新');window.scrollTo(0,0)}};
 const pullDistance=usePullRefresh(screen==='study'&&!ttsMenu,refreshPage);
 const switchScope=(all:boolean)=>{if(book){setShowAll(all);resetSession(book,page,batchSize,baseView,all)}};
 const openBook=(b:Book)=>{setActiveId(b.id);resetSession(b,0);setScreen('study')};
 const openIndex=(b:Book)=>{setActiveId(b.id);resetSession(b,0);setIndexPage(null);setIndexQuery('');setScreen('index')};
 const jumpToWord=(b:Book,w:Word)=>{const i=b.words.findIndex(x=>x.id===w.id),p=Math.max(0,Math.floor(i/b.pageSize));setActiveId(b.id);setPage(p);setSeen(new Set());setBatchIds([w.id]);setViews({[w.id]:'both'});setScreen('study')};
 const addBook=(words:Word[],name:string,pageSize:number)=>{if(!words.length)return alert('没有识别到“英文 + 中文”数据');const b=makeBook(words,name,pageSize);persist([...books,b]);setActiveId(b.id);resetSession(b,0);setScreen('study')};
 const importRaw=(raw:string)=>{const name=(document.getElementById('bookName')as HTMLInputElement)?.value||'我的词库',ps=Number((document.getElementById('pageSize')as HTMLInputElement)?.value)||50;addBook(parseText(raw),name,Math.max(10,Math.min(200,ps)))};
 const extractLegacyDocFallback=(buffer:ArrayBuffer)=>{
  const raw=new TextDecoder('utf-16le',{fatal:false}).decode(buffer);
  return raw
   .replace(/\x13\s*HYPERLINK\s+"[^"]*"(?:\s+\\t\s+"[^"]*")?\s*\x14/g,'')
   .replace(/[\x14\x15]/g,'')
   .replace(/\r\n?/g,'\n')
   .replace(/[\x00-\x08\x0b\x0c\x0e-\x12\x16-\x1f]/g,'');
 };
 const extractPdfText=async(buffer:ArrayBuffer)=>{const pdf=await getDocument({data:new Uint8Array(buffer)}).promise;const pages:string[]=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),tc=await p.getTextContent();let line='',lastY:number|undefined;const lines:string[]=[];for(const item of tc.items as any[]){if(!('str'in item))continue;const y=item.transform?.[5];if(lastY!==undefined&&typeof y==='number'&&Math.abs(y-lastY)>2){if(line.trim())lines.push(line.trim());line=''}line+=(line?' ':'')+item.str;if(typeof y==='number')lastY=y}if(line.trim())lines.push(line.trim());pages.push(lines.join('\n'))}return pages.join('\n')};
 const file=async(f:File)=>{const name=(document.getElementById('bookName')as HTMLInputElement)?.value||f.name.replace(/\.[^.]+$/,''),ps=Math.max(10,Math.min(200,Number((document.getElementById('pageSize')as HTMLInputElement)?.value)||50));let w:Word[]=[];try{if(/\.xlsx?$/i.test(f.name)){const wb=XLSX.read(await f.arrayBuffer());const rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});w=parseSheetRows(rows)}else if(/\.doc$/i.test(f.name)){const buffer=await f.arrayBuffer();const parser=(globalThis as any).docToText;const primary=parser?.(new Uint8Array(buffer));w=primary?parseText(primary):[];if(!w.length)w=parseText(extractLegacyDocFallback(buffer));if(!w.length)throw new Error('这个 DOC 没有识别到可导入的中英词条')}else if(/\.docx$/i.test(f.name)){const raw=(await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()})).value;w=parseText(raw)}else if(/\.pdf$/i.test(f.name)){w=parseText(await extractPdfText(await f.arrayBuffer()))}else{const raw=await f.text();w=/\.csv$/i.test(f.name)?parseDelimited(raw):/\.tsv$/i.test(f.name)?parseDelimited(raw,'\t'):parseText(raw)}}catch(e:any){alert(e?.message||'文件解析失败');return}addBook(w,name,ps)};
 const setAllViews=(v:View)=>{setBaseView(v);setViews(x=>({...x,...Object.fromEntries(batchIds.map(id=>[id,v]))}))};
 const cycleView=(id:string)=>setViews(v=>({...v,[id]:v[id]==='zh'?'both':v[id]==='both'?'en':'zh'}));
 // Save membership immediately; leave the rendered cards in place until refresh.
 const changeWhitelist=(ids:string[],need:boolean)=>{
  if(!book||!ids.length)return;
  const selected=new Set(ids),whitelist={...book.whitelist};
  const changedPages=new Map<string,Set<string>>();
  book.words.forEach((w,i)=>{
   if(!selected.has(w.id))return;
   const k=pageKey(Math.floor(i/book.pageSize));
   const entries=changedPages.get(k)||new Set(whitelist[k]||[]);
   need?entries.add(w.id):entries.delete(w.id);changedPages.set(k,entries);
  });
  changedPages.forEach((entries,k)=>{whitelist[k]=[...entries]});
  const updated={...book,whitelist};
  persist(books.map(b=>b.id===updated.id?updated:b));
  setListDirty(true);setRefreshNotice('');
 };
 const toggleNeed=(id:string)=>{
  if(!book)return;
  const i=book.words.findIndex(w=>w.id===id);if(i<0)return;
  changeWhitelist([id],!(book.whitelist[pageKey(Math.floor(i/book.pageSize))]||[]).includes(id));
 };
 const showCurrent=(size:number)=>{if(book)resetSession(book,page,Math.max(1,Math.floor(size)||1))};
 const nextBatch=(size=batchSize)=>{if(!book)return;const liveWhite=new Set(book.whitelist[pageKey(page)]||[]),done=new Set([...seen,...batchIds]),candidates=pageWords.filter(w=>(showAll||liveWhite.has(w.id))&&!done.has(w.id));if(!candidates.length)return;const safe=Math.min(Math.max(1,size),candidates.length),ids=candidates.slice(0,safe).map(w=>w.id);setSeen(done);setBatchIds(ids);setViews(v=>({...v,...Object.fromEntries(ids.map(id=>[id,baseView]))}));setBatchSize(size);setCustomSize(size)};
 const changePage=(n:number)=>{if(book)resetSession(book,n)};
 const renameBook=(id:string,current:string)=>{const next=prompt('重命名词库',current)?.trim();if(!next||next===current)return;persist(books.map(b=>b.id===id?{...b,name:next}:b))};
 const deleteBook=(id:string)=>{const next=books.filter(b=>b.id!==id);persist(next);if(activeId===id)setActiveId(next[0]?.id||'');if(!next.length)setScreen('import')};
 const openUrl=(url:string)=>Browser.open({url});
 const continueInstall=async()=>{if(!Capacitor.isNativePlatform())return;setChecking(true);setUpdateProgress({progress:100,state:'准备安装',source:''});try{const r=await AppUpdater.installPending();setPendingUpdate(!!r?.pending)}catch(e:any){setPendingUpdate(false);alert(e?.message||'继续安装失败')}finally{setChecking(false);setTimeout(()=>setUpdateProgress(null),1200)}};
 const checkUpdate=async()=>{if(pendingUpdate)return continueInstall();setChecking(true);setUpdateProgress(null);try{const r=await fetch(RELEASE_API,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error();const rel=await r.json(),apk=rel.assets?.find((a:{name:string})=>a.name.endsWith('.apk'));if(rel.tag_name==='v'+VERSION){alert('已经是最新版')}else if(apk&&confirm('发现新版本，现在更新？')){if(Capacitor.isNativePlatform()){const out=await AppUpdater.downloadAndInstall({url:apk.browser_download_url,digest:apk.digest||''});setPendingUpdate(!!out?.pending)}else await openUrl(apk.browser_download_url)}else if(!apk)alert('最新版本没有可用 APK')}catch(e:any){alert(e?.message||'检查更新失败，请稍后再试')}finally{setChecking(false);setTimeout(()=>setUpdateProgress(null),1200)}};
 if(screen==='about')return <main className={`shell screen-${screen}`}><header><div className="headerTitle"><b>ABOUT</b><span>Open-source · Local-first</span></div><button className="ghost" onClick={()=>setScreen(books.length?'library':'import')}>← 首页</button></header><section className="about"><div className="aboutHero"><div className="aboutMark">WD</div><div className="aboutIdentity"><span className="eyebrow">WORD DICTATION</span><h1>把默写这件事，<br/>做得足够简单。</h1><p>为实体手写板设计。没有账号，没有云端，没有多余流程。词库留在你的设备里。</p></div></div><div className="projectCard"><div className="githubBadge"><span className="githubIcon"><GitHubMark/></span><div><b>{REPO}</b><span>Open source on GitHub</span></div><span className="openArrow">↗</span></div><button className="projectHit" onClick={()=>openUrl(PROJECT_URL)} aria-label="打开 GitHub 项目"/></div><div className="aboutMeta"><div><span>VERSION</span><b>v{VERSION}</b><small>{BUILD_SHA.slice(0,7)}</small></div><div><span>AUTHOR</span><b>RT-C-6668882025</b><small>GitHub</small></div><div><span>STORAGE</span><b>Local only</b><small>无账号 · 无后端</small></div></div><div className="aboutActions"><button className="primary updateButton" disabled={checking} onClick={checkUpdate}><span>{updateProgress?updateProgress.state:checking?'正在处理…':pendingUpdate?'继续安装':'检查更新'}</span><small>{updateProgress?(updateProgress.progress?updateProgress.progress+'%':'')+(updateProgress.source?' · '+updateProgress.source:''):checking?'请稍候':pendingUpdate?'APK 已保留 · 无需重新下载':'应用内下载 · 直接安装'}</small></button><button onClick={()=>openUrl(PROJECT_URL)}><span className="buttonIcon"><GitHubMark/></span>查看源代码</button></div><div className="aboutFoot"><span>Built for handwriting, not another flashcard app.</span><b>© 2026 RT-C-6668882025</b></div></section></main>;
 if(screen==='library')return <main className={`shell screen-${screen}`}><header><div className="headerTitle"><b>WORD DICTATION</b><span>{books.length} 个词库</span></div><div className="headerActions"><button className="ghost" onClick={()=>setScreen('about')}>关于</button><button className="primary" onClick={()=>setScreen('import')}>+ 新建词库</button></div></header><section className="books">{books.map(b=>{const pages=Math.ceil(b.words.length/b.pageSize),need=Object.values(b.whitelist).reduce((n,a)=>n+a.length,0);return <article className="book" key={b.id} onClick={()=>openBook(b)}><div className="bookInfo"><strong title={b.name}>{b.name}</strong><span>{b.words.length} 词 · {pages} 页 · 每页 {b.pageSize}</span></div><div className="bookRight"><b>{need}</b><span>需要背</span><button className="ghost mini" onClick={e=>{e.stopPropagation();openIndex(b)}}>索引</button><button className="ghost mini" onClick={e=>{e.stopPropagation();renameBook(b.id,b.name)}}>重命名</button><button className="ghost mini danger" onClick={e=>{e.stopPropagation();if(confirm('删除词库“'+b.name+'”？'))deleteBook(b.id)}}>删除</button></div></article>})}</section></main>;
 if(screen==='index'&&book){const q=indexQuery.trim().toLowerCase(),rows=book.words.map((w,i)=>({w,i})).filter(({w,i})=>(indexPage===null||Math.floor(i/book.pageSize)===indexPage)&&(!q||w.en.toLowerCase().includes(q)||w.zh.toLowerCase().includes(q)));return <main className={`shell screen-${screen}`}><header><div className="headerTitle"><b title={book.name}>{book.name}</b><span>{indexPage===null?'单词索引':`第 ${indexPage+1} 页 · 选择加入白名单`} · {rows.length} 词</span></div><div className="headerActions"><button className="ghost" onClick={()=>setScreen('library')}>← 首页</button><button className="ghost" onClick={()=>setScreen('study')}>返回学习</button></div></header><section className="wordIndex"><div className="indexSearch"><input autoFocus value={indexQuery} onChange={e=>setIndexQuery(e.target.value)} placeholder="搜索英文或中文"/><span>{q?rows.length+' 个结果':(indexPage===null?'全部 ':'本页 ')+rows.length+' 词'}</span></div><div className="indexList">{rows.map(({w,i})=>{const included=(book.whitelist[pageKey(Math.floor(i/book.pageSize))]||[]).includes(w.id);return <div className="indexEntry" key={w.id}><button className="indexRow" onClick={()=>jumpToWord(book,w)}><span className="indexNo">{String(i+1).padStart(3,'0')}</span><strong>{w.en}</strong><span>{w.zh}</span><small>第 {Math.floor(i/book.pageSize)+1} 页 →</small></button><button className={'indexToggle'+(included?' included':'')} aria-label={(included?'移出白名单：':'加入白名单：')+w.en} onClick={()=>toggleNeed(w.id)}>{included?'移出白名单':'加入白名单'}</button></div>})}</div>{!rows.length&&<div className="indexEmpty">没有找到这个单词</div>}</section></main>;}
 if(screen==='import')return <main className={`shell screen-${screen}`}><header><div className="headerTitle"><b>新建词库</b><span>导入后自动固定分页</span></div><div className="headerActions"><button className="ghost" onClick={()=>setScreen('about')}>关于</button>{books.length>0&&<button className="ghost" onClick={()=>setScreen('library')}>← 首页</button>}</div></header><section className="import"><div className="importMeta"><label>词库名称<input id="bookName" placeholder="例如：专升本核心词汇"/></label><label>每页单词数<input id="pageSize" type="number" min="10" max="200" defaultValue="50"/></label></div><p>支持 TXT / CSV / TSV / Markdown / Excel / DOC / DOCX / PDF。每页默认 50 个，导入后页码和单词位置固定。</p><textarea aria-label="单词和释义" id="raw" defaultValue={demo}/><div className="row"><button className="primary" onClick={()=>importRaw((document.getElementById('raw')as HTMLTextAreaElement).value)}>创建词库</button><label className="file">选择文件<input type="file" accept=".txt,.csv,.tsv,.md,.markdown,.xlsx,.xls,.doc,.docx,.pdf" onChange={e=>e.target.files?.[0]&&file(e.target.files[0])}/></label></div></section></main>;
 if(!book)return null;

 return <main className={`shell screen-${screen}`}><header><div className="headerTitle"><b title={book.name}>{book.name}</b><span>{book.words.length} 词 · 第 {page+1}/{pageCount} 页</span></div><div className="headerActions"><button className="ghost homeBtn" onClick={()=>setScreen('library')}>← 首页</button><button className="ghost" onClick={()=>{setIndexPage(null);setIndexQuery('');setScreen('index')}}>索引</button><button className="ghost" disabled={page===0} onClick={()=>changePage(page-1)}>← 上一页</button><button className="ghost" disabled={page>=pageCount-1} onClick={()=>changePage(page+1)}>下一页 →</button><div className="voiceSettings"><button ref={voiceTrigger} className="ghost voiceTrigger" aria-label="语音设置" aria-expanded={ttsMenu} onClick={()=>setTtsMenu(v=>!v)}>语音</button>{ttsMenu&&<dialog ref={voiceDialog} className="voiceDialog" aria-label="语音设置" onCancel={e=>{e.preventDefault();setTtsMenu(false)}} onClick={e=>{if(e.target===e.currentTarget)setTtsMenu(false)}}><div className="voiceMenu"><div className="voiceMenuHead"><div><b>语音设置</b><span>{ttsStatus.installed?'KittenTTS · 已下载':'系统语音 · 可直接使用'}</span></div><button className="voiceClose" aria-label="关闭语音设置" onClick={()=>setTtsMenu(false)}>×</button></div>{(ttsBusy||ttsStatus.downloading)&&<><div className="voiceProgress"><span style={{width:ttsProgress+'%'}}/></div><div className="voiceDownloadState">{ttsState||'正在连接下载源'}</div></>}<label><span>语音引擎</span><select value={playbackEngine} onChange={e=>setPlayback(e.target.value)}><option value="system">系统语音</option>{ttsStatus.installed&&<option value="offline">KittenTTS</option>}</select></label>{ttsStatus.installed&&playbackEngine==='offline'&&<label><span>音色</span><select value={ttsVoice} onChange={e=>setVoice(Number(e.target.value))}><option value="0">男声 1</option><option value="1">女声 1</option><option value="2">男声 2</option><option value="3">女声 2</option><option value="4">男声 3</option><option value="5">女声 3</option><option value="6">男声 4</option><option value="7">女声 4</option></select></label>}<label><span>语速</span><select value={ttsSpeed} onChange={e=>setVoiceSpeed(Number(e.target.value))}><option value=".7">0.7×</option><option value="1">1.0×</option><option value="1.3">1.3×</option><option value="1.6">1.6×</option></select></label>{ttsStatus.installed?<button className="voiceDelete" disabled={ttsBusy} onClick={deleteVoice}>删除离线语音</button>:<button className="voiceDownload" disabled={ttsBusy||ttsStatus.downloading} onClick={downloadVoice}>{ttsBusy||ttsStatus.downloading?'正在下载 '+ttsProgress+'%':'下载离线语音 · 约 42 MB'}</button>}<small>{ttsStatus.installed?'KittenTTS Micro 已下载 · 8 种英文音色 · 完全离线':'不下载也能朗读 · 下载后使用 KittenTTS Micro'}</small></div></dialog>}</div></div></header>
 <div className="pullIndicator" role="status" style={{height:pullDistance?Math.min(pullDistance*.5,60):0}}>{pullDistance>=80?'松手刷新':pullDistance>0?'下拉刷新':''}</div>
 <nav className="studyNav"><div className="navGroups"><div className="seg">{([['zh','中文'],['en','英文'],['both','全部']]as const).map(([v,t])=><button key={v} className={baseView===v?'on':''} onClick={()=>setAllViews(v)}>{t}</button>)}</div><div className="countControl" aria-label="显示数量"><span>显示</span>{fixedCounts.map(n=><button key={n} disabled={!eligibleWords.length} className={batch.length===Math.min(n,eligibleWords.length)&&batchSize===n?'on':''} onClick={()=>showCurrent(n)}>{n}</button>)}<input aria-label="自定义显示数量" type="number" min="1" max={Math.max(1,eligibleWords.length)} value={customSize} onChange={e=>setCustomSize(Math.max(1,Number(e.target.value)||1))}/><button onClick={()=>showCurrent(customSize)} disabled={!eligibleWords.length}>自定义</button></div></div><div className="pageStats"><span>本页 {pageWords.length}</span><span>白名单 <b>{needWords.length}</b></span><span>显示 {batch.length}</span></div></nav>
 <div className="listToolbar"><div className="scopeControl" aria-label="显示范围"><button className={!showAll?'on':''} onClick={()=>switchScope(false)}>白名单</button><button className={showAll?'on':''} onClick={()=>switchScope(true)}>本页全部</button></div><button className="refreshButton" onClick={refreshPage} aria-label="刷新当前页">↻ 刷新</button></div>
 <p className="listHint" role="status">{refreshNotice|| (listDirty?'标记已保存 · 下拉刷新列表':'打勾移出，再点取消 · 顶部下拉刷新')}</p>
 {batch.length?<section className="grid">{batch.map(w=>{const v=views[w.id]||baseView,on=whiteIds.has(w.id);return <article key={w.id} className={'card'+(!on?' isExcluded':'')}><span className="num">{String(page*book.pageSize+pageWords.indexOf(w)+1).padStart(3,'0')}</span><button className={'word view-'+v} onClick={()=>cycleView(w.id)} title="点按切换该词显示"><span className="englishCell" aria-hidden={v==='zh'}><strong>{w.en}</strong><span className="speaker" role="button" tabIndex={v==='zh'?-1:0} aria-label={'朗读 '+w.en} onClick={e=>{e.stopPropagation();speakWord(w.en)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();speakWord(w.en)}}}><SpeakerIcon/></span></span><span className="answer" aria-hidden={v==='en'}>{w.zh}</span></button><button className={'need markButton'+(!on?' marked':'')} aria-label={(on?'移出白名单：':'加入白名单：')+w.en} aria-pressed={!on} onClick={()=>toggleNeed(w.id)}><span className="markBox" aria-hidden="true">{!on?'✓':''}</span></button></article>})}</section>:<section className="empty"><h2>{needWords.length?'选择显示数量':'本页白名单为空。'}</h2><p>{needWords.length?'选择 10–50 或输入自定义数量。':'切换到本页全部，取消勾选即可重新加入。'}</p>{!needWords.length&&<button className="primary" onClick={()=>switchScope(true)}>查看本页全部单词</button>}</section>}
 <footer><span className="footerSummary">第 {page+1} / {pageCount} 页<span> · 本轮未展示 {remaining.length}</span></span><div className="footerActions">{remaining.length>0?<button className="primary" onClick={()=>nextBatch(batchSize)}>下一批 →</button>:page<pageCount-1?<button className="primary" onClick={()=>changePage(page+1)}>下一页 →</button>:<button onClick={()=>setScreen('library')}>返回首页</button>}</div></footer>
 </main>
}

